include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    one_member_abstracts: false
    lines_longer_than_80_chars: false

custom_lint:
  rules:
    - no_material_or_cupertino
    - value_object_has_from
    - avoid_nullable:
      excludes:
        - "**/*.g.dart"
        - "**/*.freezed.dart"
        - "**/*.mocks.dart"

formatter:
  trailing_commas: preserve