include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - lib/src/generated/**
    - test/integration/test_tools/serverpod_test_tools.dart

linter:
  rules:
    unawaited_futures: true
    avoid_print: true

custom_lint:
  rules:
    - value_object_has_from
    - avoid_nullable:
      excludes:
        - "**/*.g.dart"
        - "**/*.freezed.dart"
        - "**/*.mocks.dart"
        - lib/src/generated/**

formatter:
  trailing_commas: preserve